### ISSUE TITLE
Update WET to fix timeout bug

### ISSUE THREAD

**Issue by AlexCLeduc** [PHACDataHub/django-phac_aspc-helpers#53]
This is a bug anyone working on itap is very familiar with, the session timeout dialog stays active even after the timeout elapses. 

I'm not certain what we want the behaviour to be replaced with. Perhaps just try and refresh the page, perhaps with an additional param so the server can add a "you've been logged out" message above the login form

**Comment by lucbelliveau** [comment]
This was actually fixed in WET (https://github.com/wet-boew/wet-boew/pull/9620) - if we update the WET version deployed by the helpers repo, the issue should be resolved.
